### ISSUE TITLE
見た目を整える

### ISSUE THREAD

**Issue by ngin8-beta** [2024-01-12-teamdev-Blue/tetris#14]
- [x] テトリミノの描画を整える
- [x] プレイ画面を真ん中に持ってくる
- [x] スコアを出す
- [x] Next表示画面を出す。
- [x] スタートボタン
- [x] 操作方法の表示

**Comment by fununnn** [comment]
ざっと雛形を作ってみました。好みはないので修正いただいても構いません。

**Comment by ngin8-beta** [comment]
暫定でOK。昨日そろってから調整するのでまだクローズはしない。
