### ISSUE TITLE
左右移動の実装

### ISSUE THREAD

**Issue by ngin8-beta** [2024-01-12-teamdev-Blue/tetris#7]
落ちてくるテトリミノに対して左右への操作ができないため実装が必要です。

**Comment by fununnn** [comment]
とりあえずこれをやってみます。

**Comment by fununnn** [comment]
すいません色々試してたんですが結局うまく行きません。何がおかしいかわかりますか・・・？
①gameController.js

    // キー入力時の動き
    handleKeyDown(event){
        switch(event.key){
            case 'ArrowLeft':
                this.moveLeft();
                break;           
            case 'ArrowRight':
                this.moveRight();
                break;       
        }
    }

    //イベントリスナー追加
    document.addEventListener('keydown', this.handleKeyDown.bind(this)); 

    // 左に動かす
    moveLeft() {
        if(!this.model.detectCollision(-1,0,this.model.currentTetromino)){
        this.model.moveLeft();
        this.view.render(this.model.grid,this.model.currentTetromino);
        }
    }

    // 右に動かす
    moveRight() {
        if(!this.model.detectCollision(1,0,this.model.currentTetromino)){
            this.model.moveRight();
            this.view.render(this.model.grid,this.model.currentTetromino);    
    }



②gameModel.js



// テトリミノを左に移動
moveLeft() {
	if(!this.detectCollision(-1,0,this.currentTetromino)){
		this.currentTetromino.x--;
	}
	// 現在のテトリミノを左に移動するロジック
	// 衝突のチェックもここで行う
}

// テトリミノを右に移動
moveRight() {
	if(!this.detectCollision(1,0,this.currentTetromino)){
		this.currentTetromino.x++;
	}        // 現在のテトリミノを右に移動するロジック
	// 衝突のチェックもここで行う
}

**Comment by ngin8-beta** [comment]
イベントリスナーはコンストラクタ内に書いていますか？

**Comment by fununnn** [comment]
コンストラクタ外にありました、ありがとうございます！
うまく動いたのであとでプルリクします

**Comment by ngin8-beta** [comment]
対応ありがとうございました。close
